revoke delete on table "public"."token_chains" from "anon";

revoke insert on table "public"."token_chains" from "anon";

revoke references on table "public"."token_chains" from "anon";

revoke select on table "public"."token_chains" from "anon";

revoke trigger on table "public"."token_chains" from "anon";

revoke truncate on table "public"."token_chains" from "anon";

revoke update on table "public"."token_chains" from "anon";

revoke delete on table "public"."token_chains" from "authenticated";

revoke insert on table "public"."token_chains" from "authenticated";

revoke references on table "public"."token_chains" from "authenticated";

revoke select on table "public"."token_chains" from "authenticated";

revoke trigger on table "public"."token_chains" from "authenticated";

revoke truncate on table "public"."token_chains" from "authenticated";

revoke update on table "public"."token_chains" from "authenticated";

revoke delete on table "public"."token_chains" from "service_role";

revoke insert on table "public"."token_chains" from "service_role";

revoke references on table "public"."token_chains" from "service_role";

revoke select on table "public"."token_chains" from "service_role";

revoke trigger on table "public"."token_chains" from "service_role";

revoke truncate on table "public"."token_chains" from "service_role";

revoke update on table "public"."token_chains" from "service_role";

alter table "public"."token_chains" drop constraint "token_chains_chain_id_fkey";

alter table "public"."token_creators" drop constraint "token_creators_token_chain_id_fkey";

alter table "public"."token_trades" drop constraint "token_trades_token_id_fkey1";

alter table "public"."wallet_holdings" drop constraint "wallet_holdings_token_chain_id_fkey";

alter table "public"."token_chains" drop constraint "token_platforms_pkey";

drop index if exists "public"."token_platforms_pkey";

drop table "public"."token_chains";

create table "public"."tokens" (
    "id" bigint generated by default as identity not null,
    "chain_id" bigint not null,
    "market_cap" double precision not null,
    "price" double precision not null,
    "liquidity" double precision not null,
    "token_supply" bigint not null,
    "total_trade_volume" double precision not null,
    "mint_address" character varying not null,
    "name" character varying not null,
    "symbol" character varying not null,
    "metadata" json not null,
    "updated_at" timestamp without time zone not null,
    "created_at" timestamp without time zone not null
);


alter table "public"."tokens" enable row level security;

CREATE UNIQUE INDEX token_platforms_pkey ON public.tokens USING btree (id);

alter table "public"."tokens" add constraint "token_platforms_pkey" PRIMARY KEY using index "token_platforms_pkey";

alter table "public"."tokens" add constraint "token_chains_chain_id_fkey" FOREIGN KEY (chain_id) REFERENCES chains(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."tokens" validate constraint "token_chains_chain_id_fkey";

alter table "public"."token_creators" add constraint "token_creators_token_chain_id_fkey" FOREIGN KEY (token_chain_id) REFERENCES tokens(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."token_creators" validate constraint "token_creators_token_chain_id_fkey";

alter table "public"."token_trades" add constraint "token_trades_token_id_fkey1" FOREIGN KEY (token_id) REFERENCES tokens(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."token_trades" validate constraint "token_trades_token_id_fkey1";

alter table "public"."wallet_holdings" add constraint "wallet_holdings_token_chain_id_fkey" FOREIGN KEY (token_chain_id) REFERENCES tokens(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."wallet_holdings" validate constraint "wallet_holdings_token_chain_id_fkey";

grant delete on table "public"."tokens" to "anon";

grant insert on table "public"."tokens" to "anon";

grant references on table "public"."tokens" to "anon";

grant select on table "public"."tokens" to "anon";

grant trigger on table "public"."tokens" to "anon";

grant truncate on table "public"."tokens" to "anon";

grant update on table "public"."tokens" to "anon";

grant delete on table "public"."tokens" to "authenticated";

grant insert on table "public"."tokens" to "authenticated";

grant references on table "public"."tokens" to "authenticated";

grant select on table "public"."tokens" to "authenticated";

grant trigger on table "public"."tokens" to "authenticated";

grant truncate on table "public"."tokens" to "authenticated";

grant update on table "public"."tokens" to "authenticated";

grant delete on table "public"."tokens" to "service_role";

grant insert on table "public"."tokens" to "service_role";

grant references on table "public"."tokens" to "service_role";

grant select on table "public"."tokens" to "service_role";

grant trigger on table "public"."tokens" to "service_role";

grant truncate on table "public"."tokens" to "service_role";

grant update on table "public"."tokens" to "service_role";


