create table "public"."token_platforms" (
    "id" bigint generated by default as identity not null,
    "token_id" bigint not null,
    "platform_id" bigint not null,
    "market_cap" double precision not null,
    "price" double precision not null,
    "liquidity" double precision not null,
    "token_supply" bigint not null,
    "total_trade_volume" double precision not null,
    "created_at" timestamp without time zone not null default now(),
    "updated_at" timestamp without time zone not null default now()
);


alter table "public"."token_platforms" enable row level security;

CREATE UNIQUE INDEX token_platforms_pkey ON public.token_platforms USING btree (id);

alter table "public"."token_platforms" add constraint "token_platforms_pkey" PRIMARY KEY using index "token_platforms_pkey";

alter table "public"."token_platforms" add constraint "token_platforms_platform_id_fkey" FOREIGN KEY (platform_id) REFERENCES platforms(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."token_platforms" validate constraint "token_platforms_platform_id_fkey";

alter table "public"."token_platforms" add constraint "token_platforms_token_id_fkey" FOREIGN KEY (token_id) REFERENCES tokens(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."token_platforms" validate constraint "token_platforms_token_id_fkey";

grant delete on table "public"."token_platforms" to "anon";

grant insert on table "public"."token_platforms" to "anon";

grant references on table "public"."token_platforms" to "anon";

grant select on table "public"."token_platforms" to "anon";

grant trigger on table "public"."token_platforms" to "anon";

grant truncate on table "public"."token_platforms" to "anon";

grant update on table "public"."token_platforms" to "anon";

grant delete on table "public"."token_platforms" to "authenticated";

grant insert on table "public"."token_platforms" to "authenticated";

grant references on table "public"."token_platforms" to "authenticated";

grant select on table "public"."token_platforms" to "authenticated";

grant trigger on table "public"."token_platforms" to "authenticated";

grant truncate on table "public"."token_platforms" to "authenticated";

grant update on table "public"."token_platforms" to "authenticated";

grant delete on table "public"."token_platforms" to "service_role";

grant insert on table "public"."token_platforms" to "service_role";

grant references on table "public"."token_platforms" to "service_role";

grant select on table "public"."token_platforms" to "service_role";

grant trigger on table "public"."token_platforms" to "service_role";

grant truncate on table "public"."token_platforms" to "service_role";

grant update on table "public"."token_platforms" to "service_role";


