create table "public"."tokens" (
    "id" bigint generated by default as identity not null,
    "name" character varying not null,
    "symbol" character varying,
    "mint_address" character varying,
    "usd_price" double precision,
    "created_at" timestamp without time zone,
    "updated_at" timestamp without time zone
);


alter table "public"."tokens" enable row level security;

CREATE UNIQUE INDEX tokens_mint_address_key ON public.tokens USING btree (mint_address);

CREATE UNIQUE INDEX tokens_pkey ON public.tokens USING btree (id);

alter table "public"."tokens" add constraint "tokens_pkey" PRIMARY KEY using index "tokens_pkey";

alter table "public"."tokens" add constraint "tokens_mint_address_key" UNIQUE using index "tokens_mint_address_key";

grant delete on table "public"."tokens" to "anon";

grant insert on table "public"."tokens" to "anon";

grant references on table "public"."tokens" to "anon";

grant select on table "public"."tokens" to "anon";

grant trigger on table "public"."tokens" to "anon";

grant truncate on table "public"."tokens" to "anon";

grant update on table "public"."tokens" to "anon";

grant delete on table "public"."tokens" to "authenticated";

grant insert on table "public"."tokens" to "authenticated";

grant references on table "public"."tokens" to "authenticated";

grant select on table "public"."tokens" to "authenticated";

grant trigger on table "public"."tokens" to "authenticated";

grant truncate on table "public"."tokens" to "authenticated";

grant update on table "public"."tokens" to "authenticated";

grant delete on table "public"."tokens" to "service_role";

grant insert on table "public"."tokens" to "service_role";

grant references on table "public"."tokens" to "service_role";

grant select on table "public"."tokens" to "service_role";

grant trigger on table "public"."tokens" to "service_role";

grant truncate on table "public"."tokens" to "service_role";

grant update on table "public"."tokens" to "service_role";


