create table "public"."user_wallets" (
    "id" bigint generated by default as identity not null,
    "user_id" bigint not null,
    "wallet_address" character varying not null,
    "wallet_name" crypto_wallet not null,
    "created_at" timestamp without time zone not null default now(),
    "updated_at" timestamp without time zone not null default now()
);


alter table "public"."user_wallets" enable row level security;

CREATE UNIQUE INDEX user_wallets_pkey ON public.user_wallets USING btree (id);

alter table "public"."user_wallets" add constraint "user_wallets_pkey" PRIMARY KEY using index "user_wallets_pkey";

alter table "public"."user_wallets" add constraint "user_wallets_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."user_wallets" validate constraint "user_wallets_user_id_fkey";

grant delete on table "public"."user_wallets" to "anon";

grant insert on table "public"."user_wallets" to "anon";

grant references on table "public"."user_wallets" to "anon";

grant select on table "public"."user_wallets" to "anon";

grant trigger on table "public"."user_wallets" to "anon";

grant truncate on table "public"."user_wallets" to "anon";

grant update on table "public"."user_wallets" to "anon";

grant delete on table "public"."user_wallets" to "authenticated";

grant insert on table "public"."user_wallets" to "authenticated";

grant references on table "public"."user_wallets" to "authenticated";

grant select on table "public"."user_wallets" to "authenticated";

grant trigger on table "public"."user_wallets" to "authenticated";

grant truncate on table "public"."user_wallets" to "authenticated";

grant update on table "public"."user_wallets" to "authenticated";

grant delete on table "public"."user_wallets" to "service_role";

grant insert on table "public"."user_wallets" to "service_role";

grant references on table "public"."user_wallets" to "service_role";

grant select on table "public"."user_wallets" to "service_role";

grant trigger on table "public"."user_wallets" to "service_role";

grant truncate on table "public"."user_wallets" to "service_role";

grant update on table "public"."user_wallets" to "service_role";


