revoke delete on table "public"."platforms" from "anon";

revoke insert on table "public"."platforms" from "anon";

revoke references on table "public"."platforms" from "anon";

revoke select on table "public"."platforms" from "anon";

revoke trigger on table "public"."platforms" from "anon";

revoke truncate on table "public"."platforms" from "anon";

revoke update on table "public"."platforms" from "anon";

revoke delete on table "public"."platforms" from "authenticated";

revoke insert on table "public"."platforms" from "authenticated";

revoke references on table "public"."platforms" from "authenticated";

revoke select on table "public"."platforms" from "authenticated";

revoke trigger on table "public"."platforms" from "authenticated";

revoke truncate on table "public"."platforms" from "authenticated";

revoke update on table "public"."platforms" from "authenticated";

revoke delete on table "public"."platforms" from "service_role";

revoke insert on table "public"."platforms" from "service_role";

revoke references on table "public"."platforms" from "service_role";

revoke select on table "public"."platforms" from "service_role";

revoke trigger on table "public"."platforms" from "service_role";

revoke truncate on table "public"."platforms" from "service_role";

revoke update on table "public"."platforms" from "service_role";

revoke delete on table "public"."token_platforms" from "anon";

revoke insert on table "public"."token_platforms" from "anon";

revoke references on table "public"."token_platforms" from "anon";

revoke select on table "public"."token_platforms" from "anon";

revoke trigger on table "public"."token_platforms" from "anon";

revoke truncate on table "public"."token_platforms" from "anon";

revoke update on table "public"."token_platforms" from "anon";

revoke delete on table "public"."token_platforms" from "authenticated";

revoke insert on table "public"."token_platforms" from "authenticated";

revoke references on table "public"."token_platforms" from "authenticated";

revoke select on table "public"."token_platforms" from "authenticated";

revoke trigger on table "public"."token_platforms" from "authenticated";

revoke truncate on table "public"."token_platforms" from "authenticated";

revoke update on table "public"."token_platforms" from "authenticated";

revoke delete on table "public"."token_platforms" from "service_role";

revoke insert on table "public"."token_platforms" from "service_role";

revoke references on table "public"."token_platforms" from "service_role";

revoke select on table "public"."token_platforms" from "service_role";

revoke trigger on table "public"."token_platforms" from "service_role";

revoke truncate on table "public"."token_platforms" from "service_role";

revoke update on table "public"."token_platforms" from "service_role";

alter table "public"."platforms" drop constraint "platforms_name_key";

alter table "public"."token_creators" drop constraint "token_creators_token_id_fkey";

alter table "public"."token_platforms" drop constraint "token_platforms_platform_id_fkey";

alter table "public"."token_platforms" drop constraint "token_platforms_token_id_fkey";

alter table "public"."tokens" drop constraint "tokens_chain_id_fkey";

alter table "public"."platforms" drop constraint "platforms_pkey";

alter table "public"."token_platforms" drop constraint "token_platforms_pkey";

drop index if exists "public"."platforms_name_key";

drop index if exists "public"."platforms_pkey";

drop index if exists "public"."token_platforms_pkey";

drop table "public"."platforms";

drop table "public"."token_platforms";

create table "public"."token_chains" (
    "id" bigint generated by default as identity not null,
    "chain_id" bigint not null,
    "market_cap" double precision not null,
    "price" double precision not null,
    "liquidity" double precision not null,
    "token_supply" bigint not null,
    "total_trade_volume" double precision not null,
    "created_at" timestamp without time zone not null default now(),
    "updated_at" timestamp without time zone not null default now()
);


alter table "public"."token_chains" enable row level security;

alter table "public"."token_creators" drop column "token_id";

alter table "public"."token_creators" add column "token_chain_id" bigint;

alter table "public"."tokens" drop column "chain_id";

alter table "public"."tokens" add column "token_id" bigint not null;

CREATE UNIQUE INDEX token_platforms_pkey ON public.token_chains USING btree (id);

alter table "public"."token_chains" add constraint "token_platforms_pkey" PRIMARY KEY using index "token_platforms_pkey";

alter table "public"."token_chains" add constraint "token_chains_chain_id_fkey" FOREIGN KEY (chain_id) REFERENCES chains(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."token_chains" validate constraint "token_chains_chain_id_fkey";

alter table "public"."token_creators" add constraint "token_creators_token_chain_id_fkey" FOREIGN KEY (token_chain_id) REFERENCES token_chains(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."token_creators" validate constraint "token_creators_token_chain_id_fkey";

alter table "public"."tokens" add constraint "tokens_token_id_fkey" FOREIGN KEY (token_id) REFERENCES token_chains(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."tokens" validate constraint "tokens_token_id_fkey";

grant delete on table "public"."token_chains" to "anon";

grant insert on table "public"."token_chains" to "anon";

grant references on table "public"."token_chains" to "anon";

grant select on table "public"."token_chains" to "anon";

grant trigger on table "public"."token_chains" to "anon";

grant truncate on table "public"."token_chains" to "anon";

grant update on table "public"."token_chains" to "anon";

grant delete on table "public"."token_chains" to "authenticated";

grant insert on table "public"."token_chains" to "authenticated";

grant references on table "public"."token_chains" to "authenticated";

grant select on table "public"."token_chains" to "authenticated";

grant trigger on table "public"."token_chains" to "authenticated";

grant truncate on table "public"."token_chains" to "authenticated";

grant update on table "public"."token_chains" to "authenticated";

grant delete on table "public"."token_chains" to "service_role";

grant insert on table "public"."token_chains" to "service_role";

grant references on table "public"."token_chains" to "service_role";

grant select on table "public"."token_chains" to "service_role";

grant trigger on table "public"."token_chains" to "service_role";

grant truncate on table "public"."token_chains" to "service_role";

grant update on table "public"."token_chains" to "service_role";


