create table "public"."token_trades" (
    "id" bigint generated by default as identity not null,
    "token_id" bigint not null,
    "buyer_wallet_address" character varying not null,
    "seller_wallet_address" character varying not null,
    "trade_price" double precision not null,
    "created_at" timestamp without time zone not null default now()
);


alter table "public"."token_trades" enable row level security;

CREATE UNIQUE INDEX token_trades_pkey ON public.token_trades USING btree (id);

CREATE UNIQUE INDEX token_trades_token_id_key ON public.token_trades USING btree (token_id);

alter table "public"."token_trades" add constraint "token_trades_pkey" PRIMARY KEY using index "token_trades_pkey";

alter table "public"."token_trades" add constraint "token_trades_token_id_fkey" FOREIGN KEY (token_id) REFERENCES tokens(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."token_trades" validate constraint "token_trades_token_id_fkey";

alter table "public"."token_trades" add constraint "token_trades_token_id_key" UNIQUE using index "token_trades_token_id_key";

grant delete on table "public"."token_trades" to "anon";

grant insert on table "public"."token_trades" to "anon";

grant references on table "public"."token_trades" to "anon";

grant select on table "public"."token_trades" to "anon";

grant trigger on table "public"."token_trades" to "anon";

grant truncate on table "public"."token_trades" to "anon";

grant update on table "public"."token_trades" to "anon";

grant delete on table "public"."token_trades" to "authenticated";

grant insert on table "public"."token_trades" to "authenticated";

grant references on table "public"."token_trades" to "authenticated";

grant select on table "public"."token_trades" to "authenticated";

grant trigger on table "public"."token_trades" to "authenticated";

grant truncate on table "public"."token_trades" to "authenticated";

grant update on table "public"."token_trades" to "authenticated";

grant delete on table "public"."token_trades" to "service_role";

grant insert on table "public"."token_trades" to "service_role";

grant references on table "public"."token_trades" to "service_role";

grant select on table "public"."token_trades" to "service_role";

grant trigger on table "public"."token_trades" to "service_role";

grant truncate on table "public"."token_trades" to "service_role";

grant update on table "public"."token_trades" to "service_role";


