create table "public"."wallet_holdings" (
    "id" bigint generated by default as identity not null,
    "wallet_id" bigint not null,
    "token_id" bigint not null,
    "balance" double precision not null,
    "created_at" timestamp without time zone default now(),
    "updated_at" timestamp without time zone default now()
);


alter table "public"."wallet_holdings" enable row level security;

CREATE UNIQUE INDEX wallet_holdings_pkey ON public.wallet_holdings USING btree (id);

alter table "public"."wallet_holdings" add constraint "wallet_holdings_pkey" PRIMARY KEY using index "wallet_holdings_pkey";

alter table "public"."wallet_holdings" add constraint "wallet_holdings_token_id_fkey" FOREIGN KEY (token_id) REFERENCES tokens(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."wallet_holdings" validate constraint "wallet_holdings_token_id_fkey";

alter table "public"."wallet_holdings" add constraint "wallet_holdings_wallet_id_fkey" FOREIGN KEY (wallet_id) REFERENCES user_wallets(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."wallet_holdings" validate constraint "wallet_holdings_wallet_id_fkey";

grant delete on table "public"."wallet_holdings" to "anon";

grant insert on table "public"."wallet_holdings" to "anon";

grant references on table "public"."wallet_holdings" to "anon";

grant select on table "public"."wallet_holdings" to "anon";

grant trigger on table "public"."wallet_holdings" to "anon";

grant truncate on table "public"."wallet_holdings" to "anon";

grant update on table "public"."wallet_holdings" to "anon";

grant delete on table "public"."wallet_holdings" to "authenticated";

grant insert on table "public"."wallet_holdings" to "authenticated";

grant references on table "public"."wallet_holdings" to "authenticated";

grant select on table "public"."wallet_holdings" to "authenticated";

grant trigger on table "public"."wallet_holdings" to "authenticated";

grant truncate on table "public"."wallet_holdings" to "authenticated";

grant update on table "public"."wallet_holdings" to "authenticated";

grant delete on table "public"."wallet_holdings" to "service_role";

grant insert on table "public"."wallet_holdings" to "service_role";

grant references on table "public"."wallet_holdings" to "service_role";

grant select on table "public"."wallet_holdings" to "service_role";

grant trigger on table "public"."wallet_holdings" to "service_role";

grant truncate on table "public"."wallet_holdings" to "service_role";

grant update on table "public"."wallet_holdings" to "service_role";


