create table "public"."chains" (
    "id" bigint generated by default as identity not null,
    "name" character varying not null,
    "created_at" timestamp without time zone not null default now(),
    "updated_at" timestamp without time zone not null default now()
);


alter table "public"."chains" enable row level security;

CREATE UNIQUE INDEX chains_name_key ON public.chains USING btree (name);

CREATE UNIQUE INDEX chains_pkey ON public.chains USING btree (id);

alter table "public"."chains" add constraint "chains_pkey" PRIMARY KEY using index "chains_pkey";

alter table "public"."chains" add constraint "chains_name_key" UNIQUE using index "chains_name_key";

grant delete on table "public"."chains" to "anon";

grant insert on table "public"."chains" to "anon";

grant references on table "public"."chains" to "anon";

grant select on table "public"."chains" to "anon";

grant trigger on table "public"."chains" to "anon";

grant truncate on table "public"."chains" to "anon";

grant update on table "public"."chains" to "anon";

grant delete on table "public"."chains" to "authenticated";

grant insert on table "public"."chains" to "authenticated";

grant references on table "public"."chains" to "authenticated";

grant select on table "public"."chains" to "authenticated";

grant trigger on table "public"."chains" to "authenticated";

grant truncate on table "public"."chains" to "authenticated";

grant update on table "public"."chains" to "authenticated";

grant delete on table "public"."chains" to "service_role";

grant insert on table "public"."chains" to "service_role";

grant references on table "public"."chains" to "service_role";

grant select on table "public"."chains" to "service_role";

grant trigger on table "public"."chains" to "service_role";

grant truncate on table "public"."chains" to "service_role";

grant update on table "public"."chains" to "service_role";


