create table "public"."token_creators" (
    "id" bigint generated by default as identity not null,
    "creator_id" bigint not null,
    "token_id" bigint not null,
    "total_supply" double precision not null,
    "holdings" double precision not null,
    "update_authority" character varying not null,
    "created_at" timestamp without time zone not null default now(),
    "updated_at" timestamp without time zone not null default now()
);


alter table "public"."token_creators" enable row level security;

create table "public"."token_developers" (
    "id" bigint generated by default as identity not null,
    "chain_id" bigint not null,
    "wallet_address" character varying not null,
    "created_at" timestamp without time zone not null default now(),
    "updated_at" timestamp without time zone not null default now()
);


alter table "public"."token_developers" enable row level security;

CREATE UNIQUE INDEX token_creators_pkey ON public.token_creators USING btree (id);

CREATE UNIQUE INDEX token_developer_pkey ON public.token_developers USING btree (id);

alter table "public"."token_creators" add constraint "token_creators_pkey" PRIMARY KEY using index "token_creators_pkey";

alter table "public"."token_developers" add constraint "token_developer_pkey" PRIMARY KEY using index "token_developer_pkey";

alter table "public"."token_creators" add constraint "token_creators_creator_id_fkey" FOREIGN KEY (creator_id) REFERENCES token_developers(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."token_creators" validate constraint "token_creators_creator_id_fkey";

alter table "public"."token_creators" add constraint "token_creators_token_id_fkey" FOREIGN KEY (token_id) REFERENCES tokens(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."token_creators" validate constraint "token_creators_token_id_fkey";

alter table "public"."token_developers" add constraint "token_developer_chain_id_fkey" FOREIGN KEY (chain_id) REFERENCES chains(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."token_developers" validate constraint "token_developer_chain_id_fkey";

grant delete on table "public"."token_creators" to "anon";

grant insert on table "public"."token_creators" to "anon";

grant references on table "public"."token_creators" to "anon";

grant select on table "public"."token_creators" to "anon";

grant trigger on table "public"."token_creators" to "anon";

grant truncate on table "public"."token_creators" to "anon";

grant update on table "public"."token_creators" to "anon";

grant delete on table "public"."token_creators" to "authenticated";

grant insert on table "public"."token_creators" to "authenticated";

grant references on table "public"."token_creators" to "authenticated";

grant select on table "public"."token_creators" to "authenticated";

grant trigger on table "public"."token_creators" to "authenticated";

grant truncate on table "public"."token_creators" to "authenticated";

grant update on table "public"."token_creators" to "authenticated";

grant delete on table "public"."token_creators" to "service_role";

grant insert on table "public"."token_creators" to "service_role";

grant references on table "public"."token_creators" to "service_role";

grant select on table "public"."token_creators" to "service_role";

grant trigger on table "public"."token_creators" to "service_role";

grant truncate on table "public"."token_creators" to "service_role";

grant update on table "public"."token_creators" to "service_role";

grant delete on table "public"."token_developers" to "anon";

grant insert on table "public"."token_developers" to "anon";

grant references on table "public"."token_developers" to "anon";

grant select on table "public"."token_developers" to "anon";

grant trigger on table "public"."token_developers" to "anon";

grant truncate on table "public"."token_developers" to "anon";

grant update on table "public"."token_developers" to "anon";

grant delete on table "public"."token_developers" to "authenticated";

grant insert on table "public"."token_developers" to "authenticated";

grant references on table "public"."token_developers" to "authenticated";

grant select on table "public"."token_developers" to "authenticated";

grant trigger on table "public"."token_developers" to "authenticated";

grant truncate on table "public"."token_developers" to "authenticated";

grant update on table "public"."token_developers" to "authenticated";

grant delete on table "public"."token_developers" to "service_role";

grant insert on table "public"."token_developers" to "service_role";

grant references on table "public"."token_developers" to "service_role";

grant select on table "public"."token_developers" to "service_role";

grant trigger on table "public"."token_developers" to "service_role";

grant truncate on table "public"."token_developers" to "service_role";

grant update on table "public"."token_developers" to "service_role";


